targets:
  - name: ybiframe
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publishShort/1hx7yh60big000
    open-wait-secs: 90
    after-load-wait-secs: 10
    elements-check:
      - type: iframe
        locator:
          type: css-selector
          value: "#h74i8m87jvc00 iframe"
        wait-for-content: true
        capture:
          x: 570
          y: 200
          width: 750
          height: 680
  - name: dsjiframe
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publishShort/48ydcb79222000
    open-wait-secs: 90
    after-load-wait-secs: 10
    elements-check:
      - type: iframe
        locator:
          type: css-selector
          value: "#h74i8m87jvc00 iframe"
        wait-for-content: true
        capture:
          x: 570
          y: 150
          width: 750
          height: 530
  - name: tciframe
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publishShort/2bmkieuyofok00
    open-wait-secs: 60
    after-load-wait-secs: 10  # 添加额外等待时间
    elements-check:
      - type: iframe
        locator:
          type: css-selector
          value: "#h74i8m87jvc00 iframe"
        wait-for-content: true  # 等待iframe内容加载
        capture:
          x: 570
          y: 200
          width: 750
          height: 730
  - name: gatiframe
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publishShort/3x16et99f60000
    open-wait-secs: 60
    after-load-wait-secs: 10  # 添加额外等待时间
    elements-check:
      - type: iframe
        locator:
          type: css-selector
          value: "#h74i8m87jvc00 iframe"
        wait-for-content: true  # 等待iframe内容加载
        capture:
          x: 570
          y: 230
          width: 700
          height: 730
  - name: wltiframe
    url: http://132.252.100.92:8088/#/share/a87039032dcc41abb1d045950be1d7ef
    open-wait-secs: 60
    after-load-wait-secs: 10  # 加载后额外等待5秒
    elements-check: []  # 空列表，表示不需要等待任何元素
  - name: gyiframe
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publishShort/ba95d0yijwo00
    open-wait-secs: 60
    after-load-wait-secs: 10
    elements-check:
      - type: iframe
        locator:
          type: css-selector
          value: "#\\31whtzve5qo3k00 iframe"
        wait-for-content: true
        capture:
          x: 620
          y: 220
          width: 680
          height: 500
  - name: abaaba
    url: http://132.254.207.138:38080/yitu/index.html#/chart/publish/MTg3MzUyOTkzNDQwNjc5NTI2Ng==/MTg3MzUyOTkzNDU0NTIwNzI5Nw==/MTczNTU0OTY1MzQyNg==
    open-wait-secs: 10
    elements-check:
      - type: video # iframe, element
        locator:
          type: css-selector # id, xpath
          value: "#app video.cool-video" #app video.cool-video
  - name: test123
    url: http://132.254.207.139:38080/yitu/index.html#/chart/publishShort/3q1yc0x1e1w000
    open-wait-secs: 60  # 设置等待时间为60秒，与其他类似配置保持一致
    after-load-wait-secs: 10  # 额外等待10秒
    elements-check: []  # 空列表，表示不需要等待任何元素