version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - HTTP_PROXY=http://host.docker.internal:7890
        - HTTPS_PROXY=http://host.docker.internal:7890
        - ALL_PROXY=socks5://host.docker.internal:7890
    volumes:
      - ./.history:/app/.history
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 